### ISSUE TITLE
[TODO] 데이터 EDA 수행 목록

### ISSUE THREAD

**Issue by ggm1207** [VumBleBot/Group-Activity#11]
## 📌  요약

- (수행 전) 데이터셋 분포 확인 및 패턴 발견.

- (수행 후) [데이터 EDA](https://hackmd.io/@cdll-lo-ol-lo-ol/S1sZi8pw_)

### Before
- [x] 여러가지 Feature들 고려해서 Dataframe 생성 ( 나중에 시각화가 용이한 )
- [x] Answer가 Document의 어느 위치쯤에 분포하는지 시각화
- [x] validation에서 정답이 n개인 경우 Check
- [x] 문장들의 [CLS] Token Vector - TSNE 시각화 ( Model이 유의어에 얼마나 취약한지를 보기 위함 )
    - 보류
- [x] Docs [CLS] Token Vector - TNSE 시각화 ( Document들이 어떤 식으로 군집되는지 시각화 )
    - Sparse Vector ( 시각화 할 필요 없음 )
    - Dense Vector
- [x] Docs 문서, 한글 전처리 파이프라인 한 번 체크해보기
    - 특히 답변 체크, "" 이런거나 뭐 저런거
- [x] Exact Match에 영향을 끼치는 Token들이 얼마나 있을까 체크

### After

-

**Comment by sooyounlee** [comment]
어제 말씀하신대로 질문과 evidence 문단 사이에 얼마나 많은 단어가 겹치는지도 보면 좋을 것 같아요!

**Comment by ggm1207** [comment]
넵! 그 부분은 종헌님이 한 번 해보시는 걸로 얘기가 됐습니다! @olenmg 어제 비몽사몽 얘기해서 기억이 잘 안나는데 :thinking: 하기로 했었던 것 같습니다 ㅎㅎ

**Comment by olenmg** [comment]
넵 제가 오늘 내에 해서 공유 드리겠습니다!
